[package]
name = "minnas-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
rmcp = "0.6.4"
tokio = {version = "1.47.1", features = ["rt-multi-thread", "io-std"]}
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
